#!/bin/bash
#PBS -N trans-hp2
#PBS -j oe
#PBS -l nodes=1:ppn=4:gpus=1:C6
#PBS -l mem=20gb
#PBS -l walltime=28:00:00:00
#PBS -q dept_gpu_12GB


############################
##       Environment      ##
############################
cd $PBS_O_WORKDIR
export PATH=/usr/local/bin:$PATH
export PATH=/opt/anaconda3/bin:$PATH
export LD_LIBRARY_PATH=LD_LIBRARY_PATH:/usr/local/cuda-9.0/lib64/
source activate torch


############################
##     Array Job Exec.    ##
############################
cmd="/net/pulsar/home/koes/jok120/.conda/envs/torch/bin/$(sed -n "${PBS_ARRAYID}p" cluster/190325.txt)"
echo $cmd
eval $cmd


############################
##          Exit          ##
############################
exit 0
